### ISSUE TITLE
Electrode Component - webpack test config cannot resolve error

### ISSUE THREAD

**Issue by seansean11** [electrode-io/electrode#158]
I ran into an issue when utilizing the postcss-import plugin by importing one css file into another, while using of `url` in css to import fonts.
```css
@font-face {
  font-family: 'fontello';
  src: url('../font/fontello.eot');
  src: url('../font/fontello.eot#iefix') format('embedded-opentype'),
       url('../font/fontello.woff2') format('woff2'),
       url('../font/fontello.woff') format('woff'),
       url('../font/fontello.ttf') format('truetype'),
       url('../font/fontello.svg#fontello') format('svg');
  font-weight: normal;
  font-style: normal;
}
```
This works fine when running the webpack.config.demo.dev.js configuration, but it yields errors when running the webpack.config.test.js.  The `src` alias in this config seems to be causing the `url` to need to go back an additional directory for webpack to build successfully.  Writing the code in this way would cause the `test` build to pass but the `demo dev` build to fail.
```css
@font-face {
  font-family: 'fontello';
  src: url('../../font/fontello.eot');
  src: url('../../font/fontello.eot#iefix') format('embedded-opentype'),
       url('../../font/fontello.woff2') format('woff2'),
       url('../../font/fontello.woff') format('woff'),
       url('../../font/fontello.ttf') format('truetype'),
       url('../../font/fontello.svg#fontello') format('svg');
  font-weight: normal;
  font-style: normal;
}
```

![screen shot 2017-02-09 at 9 31 02 am](https://cloud.githubusercontent.com/assets/2547722/22793893/7038dd80-eeae-11e6-98c1-5e4446f74fad.png)
